CREATE TABLE EMPLOYEE_SP
(
	EMP_CODE char(5) PRIMARY KEY,
	EMP_NAME char(20),
	DEPT_CODE char(5), FOREIGN KEY (DEPT_CODE) REFERENCES DEPARTMENT(DEPT_CODE),
	DESIG_CODE char(5), FOREIGN KEY (DESIG_CODE) REFERENCES DESIGNATION(DESIG_CODE),
	GENDER char(1),
	ADDRESS char(25),
	CITY char(20),
	STATE char(20),
	PIN char(6),
	BASIC Number,
	JN_DT Date
);
CREATE TABLE EMPLOYEE
(
	EMP_CODE char(5) PRIMARY KEY,
	EMP_NAME char(20),
	DEPT_CODE char(5),
	DESIG_CODE char(5),
	GENDER char(1),
	ADDRESS char(25),
	CITY char(20),
	STATE char(20),
	PIN char(6),
	BASIC Number,
	JN_DT Date
);

CREATE TABLE DESIGNATION
(
	DESIG_CODE char(5) Primary key, 
	DESIG_DESC char(20),
);

CREATE TABLE DEPARTMENT
(
	DEPT_CODE char(5),
	DEPT_NAME char(15) Primary key,
);

DESC EMPLOYEE;
INSERT into DESIGNATION values('man','Manager');
INSERT into DESIGNATION values('exe','Executive');
INSERT into DESIGNATION values('off','officer');
INSERT into DESIGNATION values('clk','clerk');
INSERT into DESIGNATION values('hlp','helper');

INSERT into DEPARTMENT values('1','Personnel');
INSERT into DEPARTMENT values('2','Production');
INSERT into DEPARTMENT values('3','Purchase');
INSERT into DEPARTMENT values('4','Finance');
INSERT into DEPARTMENT values('5','Research');

INSERT into EMPLOYEE values(&EMP_CODE, &EMP_NAME, &DEPT_CODE, &DESIG_CODE, &GENDER, &ADDRESS,
	&CITY, &STATE, &PIN, &BASIC, &JN_DT);
INSERT into EMPLOYEE (EMP_CODE, EMP_NAME, DESIG_CODE, GENDER, ADDRESS, CITY, STATE, PIN, JN_DT) values 
					(001, 'Amit', 'per', 'M', 'Shibpur', 'Howrah', 711101, '17-jun-2015');
					 
SELECT * from EMPLOYEE WHERE DEPT_CODE is NULL;

SELECT * from EMPLOYEE WHERE BASIC = 0;
	
SELECT * from EMPLOYEE WHERE BASIC is NULL;

SELECT avg(BASIC) from EMPLOYEE;

UPDATE EMPLOYEE set BASIC = 0 where BASIC is NULL;

SELECT avg(BASIC) from EMPLOYEE;
DELETE from EMPLOYEE where DEPT_CODE is NULL;
SELECT EMP_NAME, BASIC + BASIC*0.2 + BASIC*0.6 AS NETPAY from EMPLOYEE;

SELECT upper(EMP_NAME), BASIC from EMPLOYEE order by DEPT_CODE asc;
SELECT EMP_NAME from EMPLOYEE where JN_DT > '1-jan-2013';
SELECT count(EMP_CODE) from EMPLOYEE where JN_DT LIKE '%JAN%';
SELECT max(BASIC), min(BASIC) from EMPLOYEE;
SELECT count(EMP_CODE) from EMPLOYEE where GENDER = 'F';
UPDATE EMPLOYEE set CITY = upper(CITY);
SELECT count(DISTINCT CITY) from EMPLOYEE;
SELECT EMP_CODE, EMP_NAME, DEPT_CODE, DESIG_CODE, GENDER, ADDRESS, upper(CITY), STATE, PIN, BASIC, JN_DT from EMPLOYEE
	order by DEPT_CODE, DESIG_CODE;
---SELECT TOP 1 SALARY, EMP_NAME FROM (SELECT DISTINCT TOP n BASIC,EMP_NAME FROM EMPLOYEE ORDER BY BASIC DESC) a ORDER BY BASIC;

